name: ble_sdk
description: Bluetooth Low Energy (BLE) plugin that can communicate with single device
version: 0.2.1
homepage: https://github.com/ho-doan/ble_sdk
# publish_to: https://github.com/ho-doan/ble_sdk

environment:
  sdk: '>=2.19.4 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  protobuf: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.hodoan.ble_sdk
        pluginClass: BleSdkPlugin
      ios:
        pluginClass: BleSdkPlugin